Lesson 3 drag
AleksandrKudashkin/react-shop pull request #6
Opened 2018-08-22 02:18 UTC by AleksandrKudashkin

Попытка сделать 8е задание:
- товар можно перетаскивать
- не ясно, как правильно поступать с position. Если ставить сразу в absolute, то все товары накладываются друг на друга. Если ставить relative, то перетаскивание получается какими-то рывками. В итоге, пока я начинаю с relative, и на по mouseDown ставлю absolute. При этом изначальные координаты сохраняются в componentDidMount, чтобы absolute начинался не с 0/0.
Все это ощущается как большой костыль, но я пока не знаю лучшего варианта.
- не понятно, как сделать, чтобы добавлялся товар при наведении на компонент корзины

2018-08-22 06:42 UTC, index01d requested changes

2018-08-22 06:42 UTC, index01d commented on src/components/ProductCard.js
> +class ProductCard extends React.Component {
очень сложный путь избрал ты. 21 век же
https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API
https://www.w3schools.com/html/html5_draganddrop.asp

2018-08-22 06:42 UTC, index01d commented on src/components/ProductCard.js
> +class ProductCard extends React.Component {
даже если путь должен быть сложным,  стоит выделить отдельный компонент Draggable и не вмешивать сложную логику в код компонента карточки продукта

2020-02-13 19:40 UTC, AleksandrKudashkin commented
Пока закрою этот PR как устаревший.

2020-02-13 19:40 UTC, closed without merging